// lib/resumePdfTemplates.ts
// 6 Premium PDF Resume Templates using jsPDF

import jsPDF from "jspdf";
import { ResumeData } from "./resumeParser";

// ─── Helpers ───────────────────────────────────────────────────
function splitPts(pts: string): string[] {
  return pts.split("|").map(s => s.trim()).filter(Boolean);
}
function splitComma(s: string): string[] {
  return s.split(",").map(s => s.trim()).filter(Boolean);
}
function checkY(pdf: jsPDF, y: number, needed = 20): number {
  if (y + needed > 272) { pdf.addPage(); return 18; }
  return y;
}
function parseExtraSections(raw: string): Array<{ title: string; items: string[] }> {
  if (!raw?.trim()) return [];
  return raw.split("===").map(block => {
    const lines = block.trim().split("\n");
    const title = lines[0]?.trim() || "";
    const items = lines.slice(1).join("\n").split("|").map(s => s.trim()).filter(Boolean);
    return { title, items };
  }).filter(s => s.title && s.items.length > 0);
}

// Generic extra-sections renderer — called at end of every template
// sectionFn draws a styled section header and returns new y, bulletFn renders one item
function renderExtraSections(
  pdf: jsPDF,
  raw: string,
  getY: () => number,
  setY: (v: number) => void,
  sectionFn: (title: string) => void,
  bulletFn: (text: string) => void
) {
  const sections = parseExtraSections(raw);
  sections.forEach(({ title, items }) => {
    sectionFn(title);
    items.forEach(item => bulletFn(item));
    setY(getY() + 4);
  });
}

// ─── VALUE SUMMARY PAGE (Page 1 for all templates) ──────────────
function addValueSummaryPage(pdf: jsPDF, d: ResumeData, templateName: string) {
  const W = 210;
  // Background
  pdf.setFillColor(15, 23, 42); pdf.rect(0, 0, W, 50, "F");
  pdf.setFillColor(5, 150, 105); pdf.rect(0, 50, W, 3, "F");
  pdf.setFillColor(248, 250, 252); pdf.rect(0, 53, W, 244, "F");

  // Header
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22); pdf.setFont("helvetica", "bold");
  pdf.text("AI Resume Enhancement Report", 15, 20);
  pdf.setFontSize(10); pdf.setFont("helvetica", "normal");
  pdf.setTextColor(148, 163, 184);
  pdf.text(`Prepared for: ${d.name}  |  Template: ${templateName}  |  ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, 15, 32);
  pdf.setTextColor(167, 243, 208);
  pdf.text("Generated by Upgrade Your Resume  •  upgradeyourresume.com", 15, 42);

  let y = 68;

  // What AI did box
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(15, y, W - 30, 12, 3, 3, "F");
  pdf.setTextColor(5, 150, 105); pdf.setFontSize(12); pdf.setFont("helvetica", "bold");
  pdf.text("What AI Did To Your Resume", 22, y + 8); y += 18;

  // Improvements
  const improvements = d.aiImprovements.split("|").map(s => s.trim()).filter(Boolean);
  improvements.forEach(imp => {
    y = checkY(pdf, y, 10);
    pdf.setFillColor(240, 253, 244);
    pdf.roundedRect(15, y - 4, W - 30, 9, 2, 2, "F");
    pdf.setTextColor(5, 150, 105); pdf.setFontSize(9); pdf.setFont("helvetica", "bold");
    pdf.text(">>", 19, y + 2);
    pdf.setTextColor(17, 24, 39); pdf.setFont("helvetica", "normal");
    pdf.text(imp, 28, y + 2);
    y += 12;
  });

  y += 4;

  if (d.totalJobsFound > 0) {
    y = checkY(pdf, y, 20);
    pdf.setFillColor(239, 246, 255);
    pdf.roundedRect(15, y, W - 30, 16, 3, 3, "F");
    pdf.setDrawColor(147, 197, 253); pdf.setLineWidth(0.5);
    pdf.roundedRect(15, y, W - 30, 16, 3, 3, "S");
    pdf.setTextColor(30, 58, 138); pdf.setFontSize(10); pdf.setFont("helvetica", "bold");
    pdf.text(`All ${d.totalJobsFound} jobs included — no experience removed`, 22, y + 10);
    y += 24;
  }

  y += 4;

  // Before / After comparison
  y = checkY(pdf, y, 40);
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(15, y, W - 30, 10, 2, 2, "F");
  pdf.setTextColor(17, 24, 39); pdf.setFontSize(10); pdf.setFont("helvetica", "bold");
  pdf.text("Summary: Before vs After AI Enhancement", 22, y + 7); y += 14;

  // Before column
  pdf.setFillColor(254, 242, 242);
  pdf.roundedRect(15, y, (W - 34) / 2, 40, 2, 2, "F");
  pdf.setTextColor(220, 38, 38); pdf.setFontSize(9); pdf.setFont("helvetica", "bold");
  pdf.text("BEFORE (Original)", 20, y + 8);
  pdf.setTextColor(75, 85, 99); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8);
  pdf.text("• Responsibility-focused bullets", 20, y + 16);
  pdf.text("• Generic summary paragraph", 20, y + 23);
  pdf.text("• Skills not highlighted for ATS", 20, y + 30);
  pdf.text("• Content not ATS-optimized", 20, y + 37);

  // After column
  const col2X = 15 + (W - 34) / 2 + 4;
  pdf.setFillColor(240, 253, 244);
  pdf.roundedRect(col2X, y, (W - 34) / 2, 40, 2, 2, "F");
  pdf.setTextColor(5, 150, 105); pdf.setFontSize(9); pdf.setFont("helvetica", "bold");
  pdf.text("AFTER (AI Enhanced)", col2X + 5, y + 8);
  pdf.setTextColor(75, 85, 99); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8);
  pdf.text("• Achievement bullets with metrics", col2X + 5, y + 16);
  pdf.text("• Recruiter-optimized summary", col2X + 5, y + 23);
  pdf.text("• All jobs & bullets preserved", col2X + 5, y + 30);
  pdf.text("• ATS-friendly skills & language", col2X + 5, y + 37);

  y += 50;

  // Footer note
  y = checkY(pdf, y, 20);
  pdf.setFillColor(255, 247, 237);
  pdf.roundedRect(15, y, W - 30, 16, 3, 3, "F");
  pdf.setTextColor(194, 65, 12); pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold");
  pdf.text("Note:", 20, y + 7);
  pdf.setFont("helvetica", "normal"); pdf.setTextColor(75, 85, 99);
  pdf.text("All factual data (dates, companies, education) preserved exactly. Only writing style improved.", 38, y + 7);
  pdf.text("Review all content before submitting your resume. You can edit any field in the form.", 20, y + 13);

  // Footer bar
  pdf.setFillColor(15, 23, 42); pdf.rect(0, 284, W, 13, "F");
  pdf.setTextColor(148, 163, 184); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal");
  pdf.text("Upgrade Your Resume  •  AI Powered Career Suite  •  upgradeyourresume.com", W / 2, 292, { align: "center" });
}

// ─── TEMPLATE 1: SHARP (2-col dark sidebar) ─────────────────────
function generateSharp(pdf: jsPDF, d: ResumeData) {
  const W = 210;
  const sideW = 68;

  function drawSharpBackground() {
    pdf.setFillColor(15, 23, 42); pdf.rect(0, 0, sideW, 297, "F");
    pdf.setFillColor(248, 250, 252); pdf.rect(sideW, 0, W - sideW, 297, "F");
  }
  drawSharpBackground();

  // ── LEFT SIDEBAR ─────────────────────────────────────────
  pdf.setTextColor(255, 255, 255); pdf.setFontSize(15); pdf.setFont("helvetica", "bold");
  const nameLines = pdf.splitTextToSize(d.name || "Your Name", 56);
  pdf.text(nameLines, 8, 18);
  let ly = 18 + nameLines.length * 7;
  pdf.setFontSize(8); pdf.setFont("helvetica", "normal"); pdf.setTextColor(94, 234, 212);
  const roleLines = pdf.splitTextToSize(d.role || "Professional", 56);
  pdf.text(roleLines, 8, ly); ly += roleLines.length * 5 + 4;
  pdf.setDrawColor(5, 150, 105); pdf.setLineWidth(0.4); pdf.line(8, ly, 60, ly); ly += 6;

  // Contact
  pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(94, 234, 212);
  pdf.text("CONTACT", 8, ly); ly += 4;
  pdf.setDrawColor(30, 58, 138); pdf.setLineWidth(0.3); pdf.line(8, ly, 60, ly); ly += 5;
  pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(203, 213, 225);
  if (d.email) { const el = pdf.splitTextToSize(d.email, 54); pdf.text(el, 8, ly); ly += el.length * 4.5 + 2; }
  if (d.phone) { pdf.text(d.phone, 8, ly); ly += 5; }
  if (d.location) { pdf.text(d.location, 8, ly); ly += 8; }

  // Skills
  const skills = splitComma(d.skills);
  if (skills.length) {
    pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(94, 234, 212);
    pdf.text("SKILLS", 8, ly); ly += 4;
    pdf.setDrawColor(30, 58, 138); pdf.setLineWidth(0.3); pdf.line(8, ly, 60, ly); ly += 5;
    skills.forEach(sk => {
      if (ly > 270) return; // skip if sidebar too long
      pdf.setFillColor(30, 58, 138); pdf.roundedRect(8, ly - 3, 55, 6, 1, 1, "F");
      pdf.setFontSize(7); pdf.setTextColor(147, 197, 253); pdf.setFont("helvetica", "normal");
      pdf.text(sk.substring(0, 24), 10, ly + 1); ly += 7.5;
    });
    ly += 3;
  }

  // Education
  if (d.edu1Degree && ly < 270) {
    pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(94, 234, 212);
    pdf.text("EDUCATION", 8, ly); ly += 4;
    pdf.setDrawColor(30, 58, 138); pdf.setLineWidth(0.3); pdf.line(8, ly, 60, ly); ly += 5;
    pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
    const dl = pdf.splitTextToSize(d.edu1Degree, 54); pdf.text(dl, 8, ly); ly += dl.length * 4.5 + 1;
    pdf.setFont("helvetica", "normal"); pdf.setTextColor(148, 163, 184);
    const sl = pdf.splitTextToSize(d.edu1School, 54); pdf.text(sl, 8, ly); ly += sl.length * 4.5 + 1;
    pdf.text(d.edu1Year, 8, ly); ly += 6;
    if (d.edu2Degree && ly < 265) {
      pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
      const d2l = pdf.splitTextToSize(d.edu2Degree, 54); pdf.text(d2l, 8, ly); ly += d2l.length * 4.5 + 1;
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(148, 163, 184);
      pdf.text(d.edu2School, 8, ly); ly += 4.5;
      pdf.text(d.edu2Year, 8, ly); ly += 6;
    }
  }

  // Certifications
  if (d.certifications && ly < 265) {
    pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(94, 234, 212);
    pdf.text("CERTIFICATIONS", 8, ly); ly += 4;
    pdf.setDrawColor(30, 58, 138); pdf.setLineWidth(0.3); pdf.line(8, ly, 60, ly); ly += 5;
    splitComma(d.certifications).forEach(c => {
      if (ly > 268) return;
      pdf.setFontSize(7); pdf.setFont("helvetica", "normal"); pdf.setTextColor(203, 213, 225);
      const cl = pdf.splitTextToSize(`- ${c}`, 54); pdf.text(cl, 8, ly); ly += cl.length * 4.5 + 1;
    });
  }

  // Languages
  if (d.languages) {
    ly += 3;
    pdf.setFontSize(7); pdf.setFont("helvetica", "bold"); pdf.setTextColor(94, 234, 212);
    pdf.text("LANGUAGES", 8, ly); ly += 4;
    pdf.setDrawColor(30, 58, 138); pdf.setLineWidth(0.3); pdf.line(8, ly, 60, ly); ly += 5;
    splitComma(d.languages).forEach(l => {
      pdf.setFontSize(7); pdf.setFont("helvetica", "normal"); pdf.setTextColor(203, 213, 225);
      pdf.text(`- ${l}`, 8, ly); ly += 5;
    });
  }

  // ── RIGHT COLUMN ─────────────────────────────────────────
  let ry = 14;
  const rX = sideW + 8;
  const rW = W - sideW - 16;

  function rightNewPage() {
    pdf.addPage();
    drawSharpBackground();
    ry = 14;
  }

  function rightSection(title: string) {
    if (ry + 14 > 272) rightNewPage();
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 23, 42);
    pdf.text(title, rX, ry);
    pdf.setDrawColor(5, 150, 105); pdf.setLineWidth(0.6);
    pdf.line(rX, ry + 2, rX + rW, ry + 2);
    ry += 9;
  }

  // Summary
  if (d.summary) {
    rightSection("PROFESSIONAL SUMMARY");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    const ls = pdf.splitTextToSize(d.summary, rW);
    ls.forEach((line: string) => {
      if (ry + 5 > 272) rightNewPage();
      pdf.text(line, rX, ry); ry += 5;
    });
    ry += 6;
  }

  // Experience
  const jobs = [
    [d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
    [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
    [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
    [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
    [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
    [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
    [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points],
  ];
  let expHeaderDone = false;
  jobs.forEach(([title, co, dur, pts]) => {
    if (!title) return;
    if (!expHeaderDone) { rightSection("EXPERIENCE"); expHeaderDone = true; }
    if (ry + 14 > 272) rightNewPage();
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 23, 42);
    pdf.text(title, rX, ry);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(5, 150, 105);
    pdf.text(`${co}  .  ${dur}`, rX, ry + 5); ry += 11;
    splitPts(pts).forEach(pt => {
      if (ry + 8 > 272) rightNewPage();
      pdf.setTextColor(55, 65, 81); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`-  ${pt}`, rW);
      ls.forEach((line: string) => {
        if (ry + 5 > 272) rightNewPage();
        pdf.text(line, rX + 2, ry); ry += 5;
      });
      ry += 1;
    });
    ry += 4;
  });

  if (d.projects) {
    rightSection("KEY PROJECTS");
    splitPts(d.projects).forEach(p => {
      if (ry + 8 > 272) rightNewPage();
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${p}`, rW);
      ls.forEach((line: string) => { if (ry + 5 > 272) rightNewPage(); pdf.text(line, rX + 2, ry); ry += 5; });
      ry += 1;
    });
    ry += 4;
  }

  if (d.achievements) {
    rightSection("ACHIEVEMENTS & AWARDS");
    splitPts(d.achievements).forEach(a => {
      if (ry + 8 > 272) rightNewPage();
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${a}`, rW);
      ls.forEach((line: string) => { if (ry + 5 > 272) rightNewPage(); pdf.text(line, rX + 2, ry); ry += 5; });
      ry += 1;
    });
    ry += 4;
  }

  renderExtraSections(pdf, d.extraSections,
    () => ry, v => { ry = v; },
    title => { rightSection(title.toUpperCase()); },
    text => {
      if (ry + 8 > 272) rightNewPage();
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${text}`, rW);
      ls.forEach((line: string) => { if (ry + 5 > 272) rightNewPage(); pdf.text(line, rX + 2, ry); ry += 5; });
      ry += 1;
    }
  );

}


// ─── TEMPLATE 2: IVY (elegant single column) ─────────────────────
function generateIvy(pdf: jsPDF, d: ResumeData) {
  const W = 210;
  pdf.setFillColor(255, 255, 255); pdf.rect(0, 0, W, 297, "F");
  pdf.setFillColor(245, 240, 230); pdf.rect(0, 0, W, 42, "F");
  pdf.setDrawColor(139, 105, 60); pdf.setLineWidth(1.2); pdf.line(0, 42, W, 42);

  pdf.setTextColor(60, 40, 10); pdf.setFontSize(26); pdf.setFont("helvetica", "bold");
  pdf.text(d.name || "Your Name", W / 2, 18, { align: "center" });
  pdf.setFontSize(11); pdf.setFont("helvetica", "normal"); pdf.setTextColor(139, 105, 60);
  pdf.text(d.role || "Professional Title", W / 2, 27, { align: "center" });
  pdf.setFontSize(8); pdf.setTextColor(107, 89, 60);
  const contact = [d.email, d.phone, d.location].filter(Boolean).join("   ·   ");
  pdf.text(contact, W / 2, 36, { align: "center" });

  let y = 52;
  function ivySection(title: string) {
    if (y + 20 > 272) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255); pdf.rect(0, 0, 210, 297, "F");
      y = 18;
    }
    pdf.setFontSize(9); pdf.setFont("helvetica", "bold"); pdf.setTextColor(139, 105, 60);
    pdf.text(title, W / 2, y, { align: "center" });
    pdf.setDrawColor(139, 105, 60); pdf.setLineWidth(0.3);
    pdf.line(15, y + 2, W - 15, y + 2); y += 9;
  }

  if (d.summary) {
    ivySection("PROFILE");
    pdf.setFontSize(9); pdf.setFont("helvetica", "italic"); pdf.setTextColor(55, 45, 30);
    const ls = pdf.splitTextToSize(d.summary, W - 30); pdf.text(ls, 15, y); y += ls.length * 5.5 + 7;
  }

  [[d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
  [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
  [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
  [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
  [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
  [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
  [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points]].forEach(([title, co, dur, pts], idx) => {
    if (!title) return;
    if (idx === 0) ivySection("EXPERIENCE");
    y = checkY(pdf, y, 14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(60, 40, 10);
    pdf.text(title, 15, y);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "italic"); pdf.setTextColor(139, 105, 60);
    pdf.text(`${co}  ·  ${dur}`, 15, y + 5); y += 11;
    splitPts(pts).forEach(pt => {
      y = checkY(pdf, y, 8);
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`-  ${pt}`, W - 34);
      ls.forEach((line: string) => { y = checkY(pdf, y, 5); pdf.text(line, 20, y); y += 5; });
      y += 1;
    });
    y += 5;
  });

  const skills = splitComma(d.skills);
  if (skills.length) {
    ivySection("COMPETENCIES");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
    const skillText = splitComma(d.skills).join("  ·  ");
    const skillLines = pdf.splitTextToSize(skillText, W - 30);
    pdf.text(skillLines, W / 2, y, { align: "center" }); y += skillLines.length * 5 + 4;
  }

  if (d.edu1Degree) {
    ivySection("EDUCATION");
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(60, 40, 10);
    pdf.text(d.edu1Degree, 15, y);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "italic"); pdf.setTextColor(139, 105, 60);
    pdf.text(`${d.edu1School}  ·  ${d.edu1Year}`, 15, y + 5); y += 12;
    if (d.edu2Degree) {
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(60, 40, 10); pdf.setFontSize(10);
      pdf.text(d.edu2Degree, 15, y);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "italic"); pdf.setTextColor(139, 105, 60);
      pdf.text(`${d.edu2School}  ·  ${d.edu2Year}`, 15, y + 5); y += 12;
    }
  }

  if (d.certifications) {
    ivySection("CERTIFICATIONS");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
    pdf.text(splitComma(d.certifications).join("   ·   "), W / 2, y, { align: "center" }); y += 8;
  }
  if (d.achievements) {
    ivySection("ACHIEVEMENTS & AWARDS");
    splitPts(d.achievements).forEach(a => {
      y = checkY(pdf, y, 6);
      pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
      const ls = pdf.splitTextToSize(`-  ${a}`, W - 30); pdf.text(ls, 15, y); y += ls.length * 5.5 + 1;
    });
    y += 4;
  }
  if (d.projects) {
    ivySection("KEY PROJECTS");
    splitPts(d.projects).forEach(p => {
      y = checkY(pdf, y, 6);
      pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
      const ls = pdf.splitTextToSize(`-  ${p}`, W - 30); pdf.text(ls, 15, y); y += ls.length * 5.5 + 1;
    });
    y += 4;
  }
  if (d.languages) {
    ivySection("LANGUAGES");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
    pdf.text(splitComma(d.languages).join("   ·   "), W / 2, y, { align: "center" }); y += 8;
  }

  renderExtraSections(pdf, d.extraSections,
    () => y, v => { y = v; },
    title => { ivySection(title); },
    text => {
      y = checkY(pdf, y, 6);
      pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 45, 30);
      const ls = pdf.splitTextToSize(`-  ${text}`, W - 30); pdf.text(ls, 15, y); y += ls.length * 5.5 + 1;
    }
  );

}

// dummy ry for ivy template fix
let ry = 0;

// ─── TEMPLATE 3: SLATE (2-col teal, tech/modern) ─────────────────
function generateSlate(pdf: jsPDF, d: ResumeData) {
  const W = 210; const sideW = 72;
  pdf.setFillColor(15, 118, 110); pdf.rect(0, 0, sideW, 297, "F");
  pdf.setFillColor(247, 254, 254); pdf.rect(sideW, 0, W - sideW, 297, "F");

  // Sidebar
  pdf.setTextColor(255, 255, 255); pdf.setFontSize(15); pdf.setFont("helvetica", "bold");
  const nameL = pdf.splitTextToSize(d.name || "Your Name", 60);
  pdf.text(nameL, 8, 16);
  let ly2 = 16 + nameL.length * 7;
  pdf.setFontSize(8); pdf.setFont("helvetica", "normal"); pdf.setTextColor(153, 246, 228);
  const roleL2 = pdf.splitTextToSize(d.role || "Title", 60); pdf.text(roleL2, 8, ly2); ly2 += roleL2.length * 5 + 5;

  function slateLeft(title: string) {
    ly2 = checkY(pdf, ly2, 12);
    pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(153, 246, 228);
    pdf.text(title, 8, ly2); ly2 += 3;
    pdf.setDrawColor(20, 184, 166); pdf.setLineWidth(0.3); pdf.line(8, ly2, 64, ly2); ly2 += 5;
  }

  slateLeft("CONTACT");
  pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(204, 251, 241);
  if (d.email) { const el = pdf.splitTextToSize(d.email, 58); pdf.text(el, 8, ly2); ly2 += el.length * 4.5 + 2; }
  if (d.phone) { pdf.text(d.phone, 8, ly2); ly2 += 5; }
  if (d.location) { pdf.text(d.location, 8, ly2); ly2 += 7; }

  const skills2 = splitComma(d.skills);
  if (skills2.length) {
    slateLeft("SKILLS");
    skills2.forEach(sk => {
      ly2 = checkY(pdf, ly2, 7);
      pdf.setFillColor(13, 148, 136); pdf.roundedRect(8, ly2 - 3, 56, 6, 1, 1, "F");
      pdf.setFontSize(7); pdf.setTextColor(204, 251, 241);
      pdf.text(sk.substring(0, 24), 10, ly2 + 1); ly2 += 7;
    });
    ly2 += 3;
  }

  if (d.edu1Degree) {
    slateLeft("EDUCATION");
    pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
    const dl = pdf.splitTextToSize(d.edu1Degree, 58); pdf.text(dl, 8, ly2); ly2 += dl.length * 4.5 + 1;
    pdf.setFont("helvetica", "normal"); pdf.setTextColor(153, 246, 228);
    pdf.text(d.edu1School, 8, ly2); ly2 += 4.5;
    pdf.text(d.edu1Year, 8, ly2); ly2 += 7;
    if (d.edu2Degree) {
      pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(255, 255, 255);
      const d2l = pdf.splitTextToSize(d.edu2Degree, 58); pdf.text(d2l, 8, ly2); ly2 += d2l.length * 4.5 + 1;
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(153, 246, 228);
      pdf.text(d.edu2School, 8, ly2); ly2 += 4.5;
      pdf.text(d.edu2Year, 8, ly2); ly2 += 7;
    }
  }

  if (d.certifications) {
    slateLeft("CERTIFICATIONS");
    splitComma(d.certifications).forEach(c => {
      ly2 = checkY(pdf, ly2, 6);
      pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(204, 251, 241);
      const cl = pdf.splitTextToSize(`• ${c}`, 58); pdf.text(cl, 8, ly2); ly2 += cl.length * 4.5 + 1;
    });
  }

  if (d.languages) {
    slateLeft("LANGUAGES");
    splitComma(d.languages).forEach(l => {
      ly2 = checkY(pdf, ly2, 5);
      pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(204, 251, 241);
      pdf.text(`• ${l}`, 8, ly2); ly2 += 5;
    });
  }

  // Right content
  let ry2 = 14;
  const rX2 = sideW + 8; const rW2 = W - sideW - 16;

  function slateRight(title: string) {
    ry2 = checkY(pdf, ry2, 14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 118, 110);
    pdf.text(title, rX2, ry2);
    pdf.setDrawColor(153, 246, 228); pdf.setLineWidth(0.5); pdf.line(rX2, ry2 + 2, rX2 + rW2, ry2 + 2); ry2 += 9;
  }

  function slateCheckY(needed: number) {
    if (ry2 + needed > 272) {
      pdf.addPage();
      pdf.setFillColor(15, 118, 110); pdf.rect(0, 0, sideW, 297, "F");
      pdf.setFillColor(247, 254, 254); pdf.rect(sideW, 0, W - sideW, 297, "F");
      ry2 = 14;
    }
  }

  if (d.summary) {
    slateRight("ABOUT ME");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    const ls = pdf.splitTextToSize(d.summary, rW2); pdf.text(ls, rX2, ry2); ry2 += ls.length * 5 + 7;
  }

  [[d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
  [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
  [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
  [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
  [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
  [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
  [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points]].forEach(([title, co, dur, pts], idx) => {
    if (!title) return;
    if (idx === 0) slateRight("EXPERIENCE");
    slateCheckY(14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39);
    pdf.text(title, rX2, ry2);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(15, 118, 110);
    pdf.text(`${co}  ·  ${dur}`, rX2, ry2 + 5); ry2 += 11;
    splitPts(pts).forEach(pt => {
      slateCheckY(8);
      pdf.setTextColor(55, 65, 81); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`-  ${pt}`, rW2);
      ls.forEach((line: string) => { slateCheckY(5); pdf.text(line, rX2 + 2, ry2); ry2 += 4.5; });
      ry2 += 1;
    });
    ry2 += 4;
  });

  if (d.achievements) {
    slateRight("ACHIEVEMENTS & AWARDS");
    splitPts(d.achievements).forEach(a => {
      slateCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${a}`, rW2);
      ls.forEach((line: string) => { slateCheckY(5); pdf.text(line, rX2 + 2, ry2); ry2 += 4.5; }); ry2 += 1;
    });
    ry2 += 4;
  }

  if (d.projects) {
    slateRight("KEY PROJECTS");
    splitPts(d.projects).forEach(p => {
      slateCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${p}`, rW2);
      ls.forEach((line: string) => { slateCheckY(5); pdf.text(line, rX2 + 2, ry2); ry2 += 4.5; }); ry2 += 1;
    });
    ry2 += 4;
  }

  renderExtraSections(pdf, d.extraSections,
    () => ry2, v => { ry2 = v; },
    title => { slateRight(title.toUpperCase()); },
    text => {
      slateCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${text}`, rW2);
      ls.forEach((line: string) => { slateCheckY(5); pdf.text(line, rX2 + 2, ry2); ry2 += 4.5; }); ry2 += 1;
    }
  );

}

// ─── TEMPLATE 4: EMBER (warm tones, creative) ────────────────────
function generateEmber(pdf: jsPDF, d: ResumeData) {
  const W = 210;
  pdf.setFillColor(255, 247, 237); pdf.rect(0, 0, W, 297, "F");
  pdf.setFillColor(234, 88, 12); pdf.rect(0, 0, W, 44, "F");
  pdf.setFillColor(251, 146, 60); pdf.rect(0, 44, W, 3, "F");

  pdf.setTextColor(255, 255, 255); pdf.setFontSize(24); pdf.setFont("helvetica", "bold");
  pdf.text(d.name || "Your Name", 15, 18);
  pdf.setFontSize(11); pdf.setFont("helvetica", "normal"); pdf.setTextColor(254, 215, 170);
  pdf.text(d.role || "Professional Title", 15, 27);
  pdf.setFontSize(8); pdf.setTextColor(253, 186, 116);
  const contact3 = [d.email, d.phone, d.location].filter(Boolean).join("   |   ");
  pdf.text(contact3, 15, 36);

  let y3 = 56;
  function emberSection(title: string) {
    y3 = checkY(pdf, y3, 14);
    pdf.setFillColor(234, 88, 12); pdf.roundedRect(15, y3 - 6, 4, 12, 1, 1, "F");
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(154, 52, 18);
    pdf.text(title, 22, y3); y3 += 6;
    pdf.setDrawColor(253, 186, 116); pdf.setLineWidth(0.4); pdf.line(22, y3 - 2, W - 15, y3 - 2); y3 += 3;
  }

  if (d.summary) {
    emberSection("PROFESSIONAL SUMMARY");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    const ls = pdf.splitTextToSize(d.summary, W - 30); pdf.text(ls, 15, y3); y3 += ls.length * 5 + 7;
  }

  const skills3 = splitComma(d.skills);
  if (skills3.length) {
    emberSection("SKILLS");
    const cols3 = 3; const colW3 = (W - 30) / cols3;
    skills3.forEach((sk, i) => {
      y3 = checkY(pdf, y3, 8);
      const col = i % cols3; const row = Math.floor(i / cols3);
      if (col === 0 && row > 0) { }
      pdf.setFillColor(255, 237, 213); pdf.roundedRect(15 + col * colW3, y3 + row * 8 - 3, colW3 - 4, 7, 1, 1, "F");
      pdf.setFontSize(7.5); pdf.setTextColor(154, 52, 18); pdf.setFont("helvetica", "bold");
      pdf.text(sk.substring(0, 22), 17 + col * colW3, y3 + row * 8 + 1.5);
    });
    y3 += Math.ceil(skills3.length / cols3) * 8 + 5;
  }

  [[d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
  [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
  [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
  [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
  [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
  [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
  [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points]].forEach(([title, co, dur, pts], idx) => {
    if (!title) return;
    if (idx === 0) emberSection("EXPERIENCE");
    y3 = checkY(pdf, y3, 14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39);
    pdf.text(title, 15, y3);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(234, 88, 12);
    pdf.text(`${co}  ·  ${dur}`, 15, y3 + 5); y3 += 11;
    splitPts(pts).forEach(pt => {
      y3 = checkY(pdf, y3, 8);
      pdf.setTextColor(55, 65, 81); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`• ${pt}`, W - 32);
      ls.forEach((line: string) => { y3 = checkY(pdf, y3, 5); pdf.text(line, 18, y3); y3 += 4.5; });
      y3 += 1;
    });
    y3 += 4;
  });

  if (d.edu1Degree) {
    emberSection("EDUCATION");
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39);
    pdf.text(d.edu1Degree, 15, y3);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(234, 88, 12);
    pdf.text(`${d.edu1School}  ·  ${d.edu1Year}`, 15, y3 + 5); y3 += 12;
    if (d.edu2Degree) {
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39); pdf.setFontSize(10);
      pdf.text(d.edu2Degree, 15, y3);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(234, 88, 12);
      pdf.text(`${d.edu2School}  ·  ${d.edu2Year}`, 15, y3 + 5); y3 += 12;
    }
  }

  if (d.certifications) {
    emberSection("CERTIFICATIONS");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    pdf.text(splitComma(d.certifications).join("   ·   "), 15, y3); y3 += 8;
  }
  if (d.achievements) {
    emberSection("ACHIEVEMENTS & AWARDS");
    splitPts(d.achievements).forEach(a => {
      y3 = checkY(pdf, y3, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`• ${a}`, W - 32); ls.forEach((line: string) => { y3 = checkY(pdf, y3, 5); pdf.text(line, 18, y3); y3 += 4.5; }); y3 += 1;
    });
    y3 += 4;
  }
  if (d.projects) {
    emberSection("KEY PROJECTS");
    splitPts(d.projects).forEach(p => {
      y3 = checkY(pdf, y3, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`• ${p}`, W - 32); ls.forEach((line: string) => { y3 = checkY(pdf, y3, 5); pdf.text(line, 18, y3); y3 += 4.5; }); y3 += 1;
    });
    y3 += 4;
  }
  if (d.languages) {
    emberSection("LANGUAGES");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    pdf.text(splitComma(d.languages).join("   ·   "), 15, y3); y3 += 8;
  }

  renderExtraSections(pdf, d.extraSections,
    () => y3, v => { y3 = v; },
    title => { emberSection(title.toUpperCase()); },
    text => {
      y3 = checkY(pdf, y3, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`• ${text}`, W - 32);
      ls.forEach((line: string) => { y3 = checkY(pdf, y3, 5); pdf.text(line, 18, y3); y3 += 4.5; }); y3 += 1;
    }
  );

}

// ─── TEMPLATE 5: CLARITY (ultra minimal) ────────────────────────
function generateClarity(pdf: jsPDF, d: ResumeData) {
  const W = 210;
  pdf.setFillColor(255, 255, 255); pdf.rect(0, 0, W, 297, "F");
  pdf.setDrawColor(17, 24, 39); pdf.setLineWidth(2); pdf.line(15, 0, 15, 297);

  pdf.setTextColor(17, 24, 39); pdf.setFontSize(28); pdf.setFont("helvetica", "bold");
  pdf.text(d.name || "Your Name", 22, 20);
  pdf.setFontSize(11); pdf.setFont("helvetica", "normal"); pdf.setTextColor(107, 114, 128);
  pdf.text(d.role || "Professional Title", 22, 29);
  pdf.setFontSize(8); pdf.setTextColor(156, 163, 175);
  const contact4 = [d.email, d.phone, d.location].filter(Boolean).join("   ·   ");
  pdf.text(contact4, 22, 37);
  pdf.setDrawColor(229, 231, 235); pdf.setLineWidth(0.3); pdf.line(22, 41, W - 15, 41);

  let y4 = 50;
  function claritySection(title: string) {
    y4 = checkY(pdf, y4, 12);
    pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(156, 163, 175);
    pdf.text(title.toUpperCase(), 22, y4);
    pdf.setDrawColor(243, 244, 246); pdf.setLineWidth(0.2); pdf.line(22, y4 + 2, W - 15, y4 + 2); y4 += 8;
  }

  function clarityCheckY(needed: number) {
    if (y4 + needed > 272) {
      pdf.addPage();
      pdf.setFillColor(255, 255, 255); pdf.rect(0, 0, W, 297, "F");
      pdf.setDrawColor(17, 24, 39); pdf.setLineWidth(2); pdf.line(15, 0, 15, 297);
      y4 = 14;
    }
  }

  if (d.summary) {
    claritySection("Profile");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    const ls = pdf.splitTextToSize(d.summary, W - 37); pdf.text(ls, 22, y4); y4 += ls.length * 5.5 + 8;
  }

  [[d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
  [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
  [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
  [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
  [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
  [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
  [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points]].forEach(([title, co, dur, pts], idx) => {
    if (!title) return;
    if (idx === 0) claritySection("Experience");
    clarityCheckY(14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39);
    pdf.text(title, 22, y4);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(107, 114, 128);
    pdf.text(`${co}   ${dur}`, 22, y4 + 5); y4 += 11;
    splitPts(pts).forEach(pt => {
      clarityCheckY(8);
      pdf.setTextColor(75, 85, 99); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`-  ${pt}`, W - 40);
      ls.forEach((line: string) => { clarityCheckY(5); pdf.text(line, 25, y4); y4 += 5; });
      y4 += 1;
    });
    y4 += 5;
  });

  const skills4 = splitComma(d.skills);
  if (skills4.length) {
    claritySection("Skills");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    const sl = pdf.splitTextToSize(skills4.join("  ·  "), W - 37); pdf.text(sl, 22, y4); y4 += sl.length * 5.5 + 7;
  }

  if (d.edu1Degree) {
    claritySection("Education");
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39);
    pdf.text(d.edu1Degree, 22, y4);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(107, 114, 128);
    pdf.text(`${d.edu1School}   ${d.edu1Year}`, 22, y4 + 5); y4 += 12;
    if (d.edu2Degree) {
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(17, 24, 39); pdf.setFontSize(10);
      pdf.text(d.edu2Degree, 22, y4);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(107, 114, 128);
      pdf.text(`${d.edu2School}   ${d.edu2Year}`, 22, y4 + 5); y4 += 12;
    }
  }

  if (d.certifications) {
    claritySection("Certifications");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    pdf.text(splitComma(d.certifications).join("   ·   "), 22, y4); y4 += 8;
  }
  if (d.achievements) {
    claritySection("Achievements & Awards");
    splitPts(d.achievements).forEach(a => {
      clarityCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(75, 85, 99);
      const ls = pdf.splitTextToSize(`-  ${a}`, W - 40); ls.forEach((line: string) => { clarityCheckY(5); pdf.text(line, 25, y4); y4 += 5; }); y4 += 1;
    });
    y4 += 4;
  }
  if (d.projects) {
    claritySection("Key Projects");
    splitPts(d.projects).forEach(p => {
      clarityCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(75, 85, 99);
      const ls = pdf.splitTextToSize(`-  ${p}`, W - 40); ls.forEach((line: string) => { clarityCheckY(5); pdf.text(line, 25, y4); y4 += 5; }); y4 += 1;
    });
    y4 += 4;
  }
  if (d.languages) {
    claritySection("Languages");
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    pdf.text(splitComma(d.languages).join("   ·   "), 22, y4); y4 += 8;
  }

  renderExtraSections(pdf, d.extraSections,
    () => y4, v => { y4 = v; },
    title => { claritySection(title); },
    text => {
      clarityCheckY(6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(75, 85, 99);
      const ls = pdf.splitTextToSize(`-  ${text}`, W - 40);
      ls.forEach((line: string) => { clarityCheckY(5); pdf.text(line, 25, y4); y4 += 5; }); y4 += 1;
    }
  );

}

// ─── TEMPLATE 6: ROYAL (navy + gold, executive) ──────────────────
function generateRoyal(pdf: jsPDF, d: ResumeData) {
  const W = 210;
  pdf.setFillColor(15, 23, 42); pdf.rect(0, 0, W, 52, "F");
  pdf.setFillColor(161, 130, 60); pdf.rect(0, 52, W, 2, "F");
  pdf.setFillColor(250, 249, 246); pdf.rect(0, 54, W, 243, "F");

  pdf.setTextColor(255, 255, 255); pdf.setFontSize(24); pdf.setFont("helvetica", "bold");
  pdf.text(d.name || "Your Name", W / 2, 20, { align: "center" });
  pdf.setFontSize(11); pdf.setFont("helvetica", "normal"); pdf.setTextColor(212, 180, 110);
  pdf.text(d.role || "Professional Title", W / 2, 30, { align: "center" });
  pdf.setFontSize(8); pdf.setTextColor(148, 163, 184);
  const contact5 = [d.email, d.phone, d.location].filter(Boolean).join("   |   ");
  pdf.text(contact5, W / 2, 40, { align: "center" });

  // Gold divider dots
  pdf.setFillColor(161, 130, 60);
  [W / 2 - 20, W / 2, W / 2 + 20].forEach(x => pdf.circle(x, 48, 1, "F"));

  let y5 = 65;
  function royalSection(title: string) {
    y5 = checkY(pdf, y5, 14);
    pdf.setFontSize(9); pdf.setFont("helvetica", "bold"); pdf.setTextColor(161, 130, 60);
    pdf.text(title, W / 2, y5, { align: "center" });
    pdf.setDrawColor(161, 130, 60); pdf.setLineWidth(0.5); pdf.line(15, y5 + 2, W - 15, y5 + 2); y5 += 9;
  }

  if (d.summary) {
    royalSection("EXECUTIVE PROFILE");
    pdf.setFontSize(9); pdf.setFont("helvetica", "italic"); pdf.setTextColor(55, 65, 81);
    const ls = pdf.splitTextToSize(d.summary, W - 30); pdf.text(ls, 15, y5); y5 += ls.length * 5.5 + 7;
  }

  const skills5 = splitComma(d.skills);
  if (skills5.length) {
    royalSection("CORE COMPETENCIES");
    const mid5 = Math.ceil(skills5.length / 2);
    skills5.slice(0, mid5).forEach((sk, i) => {
      y5 = checkY(pdf, y5, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      pdf.text(`*  ${sk}`, 15, y5 + i * 5.5);
    });
    skills5.slice(mid5).forEach((sk, i) => {
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      pdf.text(`*  ${sk}`, W / 2, y5 + i * 5.5);
    });
    y5 += mid5 * 5.5 + 5;
  }

  [[d.exp1Title, d.exp1Company, d.exp1Duration, d.exp1Points],
  [d.exp2Title, d.exp2Company, d.exp2Duration, d.exp2Points],
  [d.exp3Title, d.exp3Company, d.exp3Duration, d.exp3Points],
  [d.exp4Title, d.exp4Company, d.exp4Duration, d.exp4Points],
  [d.exp5Title, d.exp5Company, d.exp5Duration, d.exp5Points],
  [d.exp6Title, d.exp6Company, d.exp6Duration, d.exp6Points],
  [d.exp7Title, d.exp7Company, d.exp7Duration, d.exp7Points]].forEach(([title, co, dur, pts], idx) => {
    if (!title) return;
    if (idx === 0) royalSection("PROFESSIONAL EXPERIENCE");
    y5 = checkY(pdf, y5, 14);
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 23, 42);
    pdf.text(title, 15, y5);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "italic"); pdf.setTextColor(161, 130, 60);
    pdf.text(`${co}   |   ${dur}`, 15, y5 + 5); y5 += 11;
    splitPts(pts).forEach(pt => {
      y5 = checkY(pdf, y5, 8);
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81); pdf.setFontSize(8.5);
      const ls = pdf.splitTextToSize(`-  ${pt}`, W - 36);
      ls.forEach((line: string) => { y5 = checkY(pdf, y5, 5); pdf.text(line, 18, y5); y5 += 4.5; });
      y5 += 1;
    });
    y5 += 4;
  });

  if (d.edu1Degree) {
    royalSection("EDUCATION");
    pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 23, 42);
    pdf.text(d.edu1Degree, 15, y5);
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(161, 130, 60);
    pdf.text(`${d.edu1School}   |   ${d.edu1Year}`, 15, y5 + 5); y5 += 12;
    if (d.edu2Degree) {
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(15, 23, 42); pdf.setFontSize(10);
      pdf.text(d.edu2Degree, 15, y5);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(161, 130, 60);
      pdf.text(`${d.edu2School}   |   ${d.edu2Year}`, 15, y5 + 5); y5 += 12;
    }
  }

  if (d.certifications) {
    royalSection("CERTIFICATIONS");
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    splitComma(d.certifications).forEach(c => {
      y5 = checkY(pdf, y5, 6);
      pdf.text(`·  ${c}`, W / 2, y5, { align: "center" }); y5 += 5.5;
    });
    y5 += 4;
  }

  if (d.achievements) {
    royalSection("ACHIEVEMENTS & AWARDS");
    splitPts(d.achievements).forEach(a => {
      y5 = checkY(pdf, y5, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${a}`, W - 36);
      ls.forEach((line: string) => { y5 = checkY(pdf, y5, 5); pdf.text(line, 18, y5); y5 += 4.5; });
      y5 += 1;
    });
    y5 += 4;
  }

  if (d.projects) {
    royalSection("KEY PROJECTS");
    splitPts(d.projects).forEach(p => {
      y5 = checkY(pdf, y5, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${p}`, W - 36);
      ls.forEach((line: string) => { y5 = checkY(pdf, y5, 5); pdf.text(line, 18, y5); y5 += 4.5; });
      y5 += 1;
    });
    y5 += 4;
  }

  if (d.languages) {
    royalSection("LANGUAGES");
    pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
    pdf.text(splitComma(d.languages).join("   ·   "), W / 2, y5, { align: "center" }); y5 += 8;
  }

  renderExtraSections(pdf, d.extraSections,
    () => y5, v => { y5 = v; },
    title => { royalSection(title.toUpperCase()); },
    text => {
      y5 = checkY(pdf, y5, 6);
      pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(55, 65, 81);
      const ls = pdf.splitTextToSize(`-  ${text}`, W - 36);
      ls.forEach((line: string) => { y5 = checkY(pdf, y5, 5); pdf.text(line, 18, y5); y5 += 4.5; }); y5 += 1;
    }
  );

}

// ─── MAIN EXPORT ────────────────────────────────────────────────
export function generateResumePdf(d: ResumeData, templateId: number, includeDeclaration: boolean = false) {
  const pdf = new jsPDF();
  const names = ["", "Sharp", "Ivy", "Slate", "Ember", "Clarity", "Royal"];
  const templateName = names[templateId] || "Sharp";

  // Page 1: Value Summary
  addValueSummaryPage(pdf, d, templateName);

  // Page 2+: Resume
  pdf.addPage();

  switch (templateId) {
    case 1: generateSharp(pdf, d); break;
    case 2: generateIvy(pdf, d); break;
    case 3: generateSlate(pdf, d); break;
    case 4: generateEmber(pdf, d); break;
    case 5: generateClarity(pdf, d); break;
    case 6: generateRoyal(pdf, d); break;
    default: generateSharp(pdf, d);
  }

  // Declaration
  if (includeDeclaration) {
    pdf.addPage();
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");
    pdf.text("Declaration", 20, 30);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "I hereby declare that all the information provided in this resume is true and correct to the best of my knowledge and belief.",
      20, 45, { maxWidth: 170 }
    );
    pdf.text(`Name: ${d.name}`, 20, 70);
    pdf.text(`Date: ${new Date().toLocaleDateString("en-IN")}`, 20, 80);
  }
  
  pdf.save(`Resume_${templateName}_UpgradeYourResume.pdf`);
}
